version: '3.5'
services:
  orm-service:
    build:
      context: ""
      dockerfile: Dockerfile.jvm
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quarkus_test
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
